#![no_std]

pub trait ComplexField {
    fn norm_squared(self) -> Self;
}

pub trait Marker {}

// Nothing here has a `#[cfg]`: the gate that decides whether these impls exist
// sits on the *invocations* below, which is the whole reason the impl needs a
// key that survives expansion.
macro_rules! impl_complex {
    ($($T:ty),*) => {$(
        impl ComplexField for $T {
            fn norm_squared(self) -> Self {
                self
            }
        }
    )*};
}

macro_rules! impl_marker {
    ($($T:ty),*) => {$(
        impl Marker for $T {}
    )*};
}

// The arm a no_std build can have.
#[cfg(all(not(feature = "std"), not(feature = "libm_force"), feature = "libm"))]
impl_complex!(f32, f64);

// The arm a std-on pass selects — and a std-on pass is where these records come
// from, since a crate missing the impl does not type check.
#[cfg(all(feature = "std", not(feature = "libm_force")))]
impl_complex!(f32, f64);

// Hand-written, not generated by `impl_complex!`. It is an impl of the same
// trait for the same type, and it is deliberately *not* one of the macro's arms:
// "the same macro generates the same impls" is the inference, and it does not
// extend to a block someone wrote out by hand.
#[cfg(feature = "libm_force")]
impl ComplexField for f64 {
    fn norm_squared(self) -> Self {
        self
    }
}

// An ungated invocation. Whatever it generates is there in every configuration,
// so a call resolving into it requires nothing.
impl_marker!(f32, f64);
